[versions]
agp = "9.0.0"
composeCompiler = "2.2.10"
composeUi = "1.10.2"
composeFoundation = "1.10.2"
composeMaterial = "1.7.8"
composeMaterial3 = "1.4.0"
activity = "1.12.2"
navigation = "2.9.6"
appcompat = "1.7.1"
corektx = "1.17.0"
material = "1.12.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "corektx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
material = { module = "com.google.android.material:material", version.ref = "material" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeFoundation" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUi" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeMaterial" }
compose-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "composeUi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composeCompiler" }
